require "eye"
require "json"
require "celluloid/redis"
require "celluloid/io"

require_relative "./eye-control/version"
require_relative "./eye-control/extension/controller"
require_relative "./eye-control/extension/config_opts"
require_relative "./eye-control/extension/process"
require_relative "./eye-control/redis_manager"
